config/routes.rb
Rails.application.routes.draw do

  resources :admins

  resources :positions

  resources :applicants

  root 'static_pages#home'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
end

app/models/applicant.rb
class Applicant < ActiveRecord::Base
end

app/models/position.rb
class Position < ActiveRecord::Base
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :set_admin, only: [:show, :edit, :update, :destroy]

  # GET /admins
  # GET /admins.json
  def index
    @admins = Admin.all
  end

  # GET /admins/1
  # GET /admins/1.json
  def show
  end

  # GET /admins/new
  def new
    @admin = Admin.new
  end

  # GET /admins/1/edit
  def edit
  end

  # POST /admins
  # POST /admins.json
  def create
    @admin = Admin.new(admin_params)

    respond_to do |format|
      if @admin.save
        format.html { redirect_to @admin, notice: 'Admin was successfully created.' }
        format.json { render :show, status: :created, location: @admin }
      else
        format.html { render :new }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admins/1
  # PATCH/PUT /admins/1.json
  def update
    respond_to do |format|
      if @admin.update(admin_params)
        format.html { redirect_to @admin, notice: 'Admin was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin }
      else
        format.html { render :edit }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admins/1
  # DELETE /admins/1.json
  def destroy
    @admin.destroy
    respond_to do |format|
      format.html { redirect_to admins_url, notice: 'Admin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin
      @admin = Admin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_params
      params.require(:admin).permit(:username, :password, :status)
    end
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  before_action :set_applicant, only: [:show, :edit, :update, :destroy]

  # GET /applicants
  # GET /applicants.json
  def index
    @applicants = Applicant.all
  end

  # GET /applicants/1
  # GET /applicants/1.json
  def show
  end

  # GET /applicants/new
  def new
    @applicant = Applicant.new
  end

  # GET /applicants/1/edit
  def edit
  end

  # POST /applicants
  # POST /applicants.json
  def create
    @applicant = Applicant.new(applicant_params)

    respond_to do |format|
      if @applicant.save
        format.html { redirect_to @applicant, notice: 'Applicant was successfully created.' }
        format.json { render :show, status: :created, location: @applicant }
      else
        format.html { render :new }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applicants/1
  # PATCH/PUT /applicants/1.json
  def update
    respond_to do |format|
      if @applicant.update(applicant_params)
        format.html { redirect_to @applicant, notice: 'Applicant was successfully updated.' }
        format.json { render :show, status: :ok, location: @applicant }
      else
        format.html { render :edit }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applicants/1
  # DELETE /applicants/1.json
  def destroy
    @applicant.destroy
    respond_to do |format|
      format.html { redirect_to applicants_url, notice: 'Applicant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_applicant
      @applicant = Applicant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def applicant_params
      params[:applicant].permit(:name, :description)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, only: [:show, :edit, :update, :destroy]

  # GET /positions
  # GET /positions.json
  def index
    @positions = Position.all
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
  end

  # GET /positions/new
  def new
    @position = Position.new
  end

  # GET /positions/1/edit
  def edit
  end

  # POST /positions
  # POST /positions.json
  def create
    @position = Position.new(position_params)

    respond_to do |format|
      if @position.save
        format.html { redirect_to @position, notice: 'Position was successfully created.' }
        format.json { render :show, status: :created, location: @position }
      else
        format.html { render :new }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positions/1
  # PATCH/PUT /positions/1.json
  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to @position, notice: 'Position was successfully updated.' }
        format.json { render :show, status: :ok, location: @position }
      else
        format.html { render :edit }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position.destroy
    respond_to do |format|
      format.html { redirect_to positions_url, notice: 'Position was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def position_params
      params.require(:position).permit(:name, :description, :open)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def aboutus
  end

  def services
  end

  def carreers
  end

  def contactus
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admins/_form.html.erb
<%= form_for @admin, :html => { :class => "form-horizontal admin" } do |f| %>

  <% if @admin.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @admin.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :username, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :username, :class => 'form-control' %>
    </div>
    <%=f.error_span(:username) %>
  </div>
  <div class="form-group">
    <%= f.label :password, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :password, :class => 'form-control' %>
    </div>
    <%=f.error_span(:password) %>
  </div>
  <div class="form-group">
    <%= f.label :status, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :status, :class => 'form-control' %>
    </div>
    <%=f.error_span(:status) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admins_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/admins/edit.html.erb
<%- model_class = Admin -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admins/index.html.erb
<%- model_class = Admin -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:username) %></th>
      <th><%= model_class.human_attribute_name(:password) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= link_to admin.id, admin_path(admin) %></td>
        <td><%= admin.username %></td>
        <td><%= admin.password %></td>
        <td><%= admin.status %></td>
        <td><%=l admin.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_path(admin), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_path(admin),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_path,
            :class => 'btn btn-primary' %>

app/views/admins/new.html.erb
<%- model_class = Admin -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admins/show.html.erb
<%- model_class = Admin -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:username) %>:</strong></dt>
  <dd><%= @admin.username %></dd>
  <dt><strong><%= model_class.human_attribute_name(:password) %>:</strong></dt>
  <dd><%= @admin.password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @admin.status %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              admins_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_path(@admin), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_path(@admin),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/applicants/_form.html.erb
<%= form_for @applicant, :html => { :class => "form-horizontal applicant" } do |f| %>

  <% if @applicant.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@applicant.errors.count, "error") %> prohibited this applicant from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @applicant.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                applicants_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/applicants/edit.html.erb
<%- model_class = Applicant -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/applicants/index.html.erb
<%- model_class = Applicant -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @applicants.each do |applicant| %>
      <tr>
        <td><%= link_to applicant.id, applicant_path(applicant) %></td>
        <td><%= applicant.name %></td>
        <td><%= applicant.description %></td>
        <td><%=l applicant.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_applicant_path(applicant), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      applicant_path(applicant),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_applicant_path,
            :class => 'btn btn-primary' %>

app/views/applicants/new.html.erb
<%- model_class = Applicant -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/applicants/show.html.erb
<%- model_class = Applicant -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @applicant.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @applicant.description %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              applicants_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_applicant_path(@applicant), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              applicant_path(@applicant),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TechResource" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/89f2f44ba07ea3fff7e561c2142813b278c2d6c6/devicon.min.css">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
    <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
  </head>
  <body>
    <div class="navbar navbar-default  navbar-fixed-top" role="navigation">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <a href="#" class="navbar-brand tr-logo-link">

          <%=image_tag "tr-logo-160-white.png",  :class => "tr-logo" %>

        </a>
        <!--
        <%= link_to "TR", root_path, class: "navbar-brand topnav" %>

        -->
        <div class="navbar-collapse collapse navbar-responsive-collapse">
         <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'About Us', root_path(:anchor=>"aboutus") %></li>
            <li><%= link_to 'Careers', root_path(:anchor=>"carreers") %></li>
            <li><%= link_to 'Contact Us', root_path(:anchor=>"contactus") %></li>
            <li><span class="bfh-countries" data-country="US" data-flags="true"></span></li>
          </ul>
        </div>
      </div>
    </div>
    <%= bootstrap_flash %>
    <%= yield %>
    <%= render "static_pages/aboutus" %>
    <%= render "static_pages/carreers" %>
    <%= render "static_pages/contactus" %>
    <%= render "static_pages/footer" %>
  </body>
</html>

app/views/positions/_form.html.erb
<%= form_for @position, :html => { :class => "form-horizontal position" } do |f| %>

  <% if @position.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@position.errors.count, "error") %> prohibited this position from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @position.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <%= f.label :open, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :open, :class => 'form-control' %>
    </div>
    <%=f.error_span(:open) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                positions_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/positions/edit.html.erb
<%- model_class = Position -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/positions/index.html.erb
<%- model_class = Position -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:open) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @positions.each do |position| %>
      <tr>
        <td><%= link_to position.id, position_path(position) %></td>
        <td><%= position.name %></td>
        <td><%= position.description %></td>
        <td><%= position.open %></td>
        <td><%=l position.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_position_path(position), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      position_path(position),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_position_path,
            :class => 'btn btn-primary' %>

app/views/positions/new.html.erb
<%- model_class = Position -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/positions/show.html.erb
<%- model_class = Position -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @position.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @position.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:open) %>:</strong></dt>
  <dd><%= @position.open %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              positions_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_position_path(@position), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              position_path(@position),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/static_pages/_aboutus.html.erb
<section id="aboutus" data-speed="4" data-type="background">
  <div class="container text-center">
    <h1>About our company</h1>
    <hr>
    <div class="row-fluid">
        <div class="span4 text-justfy">
          <p>TechResource, Inc. provides one of the best Cloud-based communication services to leading companies in Asia.</p>
          <p>We employ the latest technology as our resource to accommodate the client's demands and achieve the customer's utmost satisfaction.</p>
        </div>
    </div>
  </div>
</section>

app/views/static_pages/_carreers.html.erb
<section id="carreers" data-speed="4" data-type="background">
    <div class="container">
      <div class="row-fluid text-center">
        <h1>Join our team!</h1>
        <hr class="white">
          <div class="col-sm-4">
            <i class="devicon-php-plain"></i>
            <i class="devicon-ruby-plain"></i>
              <h2>Web Developer</h2>
              <p>Develops the company's software with IP-PBX, software phones and front-end and back-end web development</p>
          </div>
          <div class="col-sm-4">
            <i class="devicon-redhat-plain-wordmark"></i>
            <i class="devicon-linux-plain"></i>
              <h2>Network Engineer</h2>
              <p>Designs and manages the business' structure, theetwork and Web servers. Well informed with Asterisk, Cisco, Linux, and VoIP</p>
          </div>
          <div class="col-sm-4">
            <i class="devicon-apple-original"></i>
            <i class="devicon-safari-line-wordmark"></i>
              <h2>Administrator</h2>
              <p>Handles the company's general affairs and provides customer support</p>
          </div>
        </div>
        <div class="row-fluid">
          <div class="col-lg-12 text-center">
                  <br>
                  <a href="http://job-search.jobstreet.com.ph/philippines/company/techresource-inc-jobs/" class="btn btn-default btn-lg">  <span class="network-name">Apply!</span></a>
        </div>
      </div>
</section>

app/views/static_pages/_intro.html.erb
<!-- Section #1 -->
  <section id="intro" data-speed="6" data-type="background">
    <div class="container">
      <!--
      <div class="row-fluid">
            <div class="col-md-4 text-center">
              <%=image_tag "desktop.png" %>
            </div>
            <div class="col-md-8 text-center">
              <%=image_tag "title.png" %>
            </div>
        </div>
      -->
        <h3> TechResource <small> | Makati/Clark<small></h3> 
        <hr>
      </div>
  </section>

app/views/static_pages/_services.html.erb
<h1>StaticPages#services</h1>
<p>Find me in app/views/static_pages/services.html.erb</p>